.cache: &cache
  cache:
    key: "$CI_BUILD_REF_NAME"
    paths:
      - eenv/
      - eenv3/

stages:
    - lint
    - test

variables:
  GIT_SUBMODULE_STRATEGY: none

before_script:
    - "[ -s \"$HOME/.gitlab_runner.sh\" ] && . $HOME/.gitlab_runner.sh"
    - "[ -s 'eenv/bin/activate' ] || virtualenv eenv"
    - "[ -s 'eenv3/bin/activate' ] || virtualenv eenv3 -p $(which python3.5 | which python3)"
    - git submodule sync --recursive
    - git submodule foreach --recursive git clean -fxd
    - git submodule update --init --recursive --force
    # for debugging some weird issues on some ci runners
    - locale
    - which python

# ############################################################################
# lint stage
# ############################################################################

flake2:
  tags:
    - shell
  stage: lint
  allow_failure: false
  retry:
      max: 2
      when:
        - runner_system_failure
  script:
    - "[ -s 'eenv/bin/activate' ] && . eenv/bin/activate"
    - python -V
    - pip install -U flake8
    - python -m flake8 pwdtk --exclude=pwdtk/testproject/manage21.py


flake3:
  tags:
    - shell
  stage: lint
  allow_failure: false
  retry:
      max: 2
      when:
        - runner_system_failure
  script:
    - "[ -s 'eenv3/bin/activate' ] && . eenv3/bin/activate"
    - python -V
    - pip install -U flake8
    - python -m flake8 pwdtk



# ############################################################################
# Test stage
# ############################################################################
test_18:
  tags:
    - shell
  stage: test
  allow_failure: false
  retry:
      max: 2
      when:
        - runner_system_failure
  script:
    - python -V
    - pip install -U tox
    - tox -e py27-django18,py35-django18,py36-django18

test_1:
  tags:
    - shell
  stage: test
  allow_failure: false
  retry:
      max: 2
      when:
        - runner_system_failure
  script:
    - python -V
    - pip install -U tox
    - tox -e py27-django1,py35-django1,py36-django1

test_21:
  tags:
    - shell
  stage: test
  allow_failure: true
  retry:
      max: 2
      when:
        - runner_system_failure
  script:
    - python -V
    - pip install -U tox
    - tox -e py35-django21,py36-django21

