language: python
matrix:
 include:
 - python: 2.7
   env: DJANGO_VERSION=18
 - python: 2.7
   env: DJANGO_VERSION=1
 - python: 3.5
   env: DJANGO_VERSION=18
 - python: 3.5
   env: DJANGO_VERSION=1
# - python: 3.5
#   env: DJANGO_VERSION=21
 - python: 3.6
   env: DJANGO_VERSION=18
 - python: 3.6
   env: DJANGO_VERSION=1
# django 1_11 with old MIDDLEWARE_CLASSES
 - python: 3.6
   env: DJANGO_VERSION=1_11_mwc
# - python: 3.6
#   env: DJANGO_VERSION=21

install:
  - pip install tox
script:
  - tox -e $(echo py${TRAVIS_PYTHON_VERSION}-django${DJANGO_VERSION} | tr -d .)
notifications:
  email:
    - feenes@teledomic.eu
