language: python
matrix:
 include:
 - python: 2.7
   env: DJANGO_VER_OR_TAG=lint
 - python: 2.7
   env: DJANGO_VER_OR_TAG=django18
 - python: 2.7
   env: DJANGO_VER_OR_TAG=django1
 - python: 3.5
   env: DJANGO_VER_OR_TAG=django18
 - python: 3.5
   env: DJANGO_VER_OR_TAG=django1
# - python: 3.5
#   env: DJANGO_VER_OR_TAG=django21
 - python: 3.6
   env: DJANGO_VER_OR_TAG=lint
 - python: 3.6
   env: DJANGO_VER_OR_TAG=django18
 - python: 3.6
   env: DJANGO_VER_OR_TAG=django1
# django 1_11 with old MIDDLEWARE_CLASSES
 - python: 3.6
   env: DJANGO_VER_OR_TAG=django1_11_mwc
# - python: 3.6
#   env: DJANGO_VER_OR_TAG=django21

install:
  - pip install tox
script:
  - tox -e $(echo py${TRAVIS_PYTHON_VERSION}-${DJANGO_VER_OR_TAG} | tr -d .)
notifications:
  email:
    - feenes@teledomic.eu
